version: '3'

services:
  dominika_scraper_1:
    container_name: dominika_scraper_1
    build: .
    volumes:
      - .:/app
    command: irb
    stdin_open: true
    tty: true
    networks:
      - hribar_proxy_net
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:4.0.0-alpha-6-20200730
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  hribar_proxy_net:
    external:
      name: hribar_net
