source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rerun'
gem 'activesupport'
gem 'activerecord'
gem 'awesome_print'
gem 'dotenv'
gem 'rake'
gem 'httparty'
gem 'nokogiri'
gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
gem 'pry-byebug'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'rubyXL'
gem 'colorize'
gem 'watir'
gem 'selenium-webdriver'
